<?php

// <auto-generated/>
// Flame Core File

// These are currently unavalible
// use Views\Files\FlameFile;
// $__generated___FlameViewFile_____ = new FlameFile(__FILE__);
// $_VIEW = $__generated___FlameViewFile_____;

?>